# site settings
encoding: utf-8
title: 문동준
baseurl: "/Resume"
url: "https://mdj0126.github.io/"
  
# author settings
author:
  name_en: moondongjun
  name_ko: 문동준
  email: ehdwns0126@naver.com
  phone: 010-2359-0126
  selfie: assets/img/profile.jpg
  job: 게임 클라이언트 프로그래머
  job_start_date: 20180903
  
# build settings

exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: compressed