# site settings
encoding: utf-8
baseurl: "/Resume"
thumbnail: "/assets/img/picture/profile.png"
title: "문동준 프로필"
desc: "Unity와 C#을 활용한 게임 클라이언트 개발자. 포트폴리오에서 프로젝트를 확인하세요!"
site_banner: "Hello, I'm dongjun moon, a game programmer."
open_to_work: true

# author settings
author:
  picture: "/assets/img/picture/profile.png"
  name_en: "Dongjun Moon"
  name_ko: "문동준"
  birth_date: "19930126"
  email: "ehdwns0126@naver.com"
  address: "경기도 부천시 원미구 역곡동"
  phone: "010-2359-0126"
  job: "게임 클라이언트 개발자"
  job_start_date: "20180903"
  coffee_chat_url: "https://open.kakao.com/o/sWoSndmh"

# site
tistory: "https://moondongjun.tistory.com/"
github: "https://github.com/MDJ0126/"
linkedin: "https://www.linkedin.com/in/moondongjun/"
  
# build settings

exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: compressed