# site settings
encoding: utf-8
title: 문동준
baseurl: "/Resume"
open_to_work: true

# author settings
author:
  name_en: moondongjun
  name_ko: 문동준
  email: ehdwns0126@naver.com
  phone: 010-2359-0126
  job: 게임 클라이언트 프로그래머
  job_start_date: 20180903
  coffee_chat_url: "https://open.kakao.com/o/sWoSndmh"
  
# build settings

exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: compressed